// project-3/client/react-project/src/components/Footer/Footer.js
import React from 'react'
import './Footer.css'
import { Link } from 'react-router-dom'
import {
  FaFacebook,
  FaInstagram,
  FaYoutube,
  FaTwitter,
  FaLinkedin,
} from 'react-icons/fa'
import { MdFingerprint } from 'react-icons/md'
import logo from '../../libs/Travelays-Logo.png'
import ScrollToTop from '../BackToTopButton/ScrollToTop'

function Footer() {
  return (
    <div className="footer-container">
      <ScrollToTop />
      <div className="footer-links">
        <div className="footer-link-wrapper">
          <div className="footer-link-items">
            <h2>About Us</h2>
            <Link to="/">How it works</Link>
            <Link to="/">Testimonials</Link>
            <Link to="/">Careers</Link>
            <Link to="/">Investors</Link>
            <Link to="/">Terms of Service</Link>
          </div>
          <div className="footer-link-items">
            <h2>Contact Us</h2>
            <Link to="/">Contact</Link>
            <Link to="/">Support</Link>
            <Link to="/">Destinations</Link>
            <Link to="/">Sponsorships</Link>
          </div>
        </div>
        <div className="footer-link-wrapper">
          <div className="footer-link-items">
            <h2>Social Media</h2>
            <Link to="/">Instagram</Link>
            <Link to="/">Facebook</Link>
            <Link to="/">Youtube</Link>
            <Link to="/">Twitter</Link>
          </div>
        </div>
      </div>
      <section className="social-media">
        <div className="social-media-wrap">
          <div className="footer-logo">
            <Link to="/" className="social-logo">
              <MdFingerprint className="navbar-icon" />
              <img className="logoImgFooter" src={logo} alt="travelays-logo" />
            </Link>
          </div>
          <small className="website-rights">TRAVELAYS © 2023</small>
          <div className="social-icons">
            <Link className="social-icon-link" to="/" aria-label="Facebook">
              <FaFacebook />
            </Link>
            <Link className="social-icon-link" to="/" aria-label="Instagram">
              <FaInstagram />
            </Link>
            <Link className="social-icon-link" to="/" aria-label="Youtube">
              <FaYoutube />
            </Link>
            <Link className="social-icon-link" to="/" aria-label="Twitter">
              <FaTwitter />
            </Link>
            <Link className="social-icon-link" to="/" aria-label="LinkedIn">
              <FaLinkedin />
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}

export default Footer

// project-4/angular-client/src/app/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {

  scrollToTop(){
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

<footer>
  <button (click)="scrollToTop()" class="back-to-top-btn">Back To Top</button>
  <div class="footer-container">
    <div class="footer-links">
      <div class="footer-link-wrapper">
        <div class="footer-link-items">
          <h2>About Us</h2>
          <a href="about">How it works</a>
          <a href="about">Testimonials</a>
          <a href="about">Careers</a>
          <a href="about">Investors</a>
          <a href="about">Terms of Service</a>
        </div>
        <div class="footer-link-items">
          <h2>Contact Us</h2>
          <a href="/">Contact</a>
          <a href="/">Support</a>
          <a href="/">Destinations</a>
          <a href="/">Sponsorships</a>
        </div>
      </div>
      <div class="footer-link-wrapper">
        <div class="footer-link-items">
          <h2>Social Media</h2>
          <a href="/">Instagram</a>
          <a href="/">Facebook</a>
          <a href="/">Youtube</a>
          <a href="/">Twitter</a>
        </div>
      </div>
    </div>
    <section class="social-media">
      <div class="social-media-wrap">
        <div>
          <a title="Vstore" class="footer-logo" href="/">Vstore</a>
        </div>
        <small class="website-rights">VSTORE © 2023</small>
        <div class="social-icons">
          <a class="social-icon-link" href="/">
            <mat-icon>facebook</mat-icon>
          </a>
          <a class="social-icon-link" href="/">
            <mat-icon>youtube_searched_for</mat-icon>
          </a>
          <a class="social-icon-link" href="/">
            <mat-icon>alternate_email</mat-icon>
          </a>
          <a class="social-icon-link" href="/">
            <mat-icon>linked_camera</mat-icon>
          </a>
        </div>
      </div>
    </section>
  </div>
</footer>
